- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Pre-requisites
  ansible.builtin.include_tasks: app_prereq.yml

- name: Download Dependencies
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
    chdir: /app

- name: Systemd Service adding
  ansible.builtin.include_tasks: systemd.yml