- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: App Pre-requisites
  ansible.builtin.include_tasks: app_prereq.yml

- name: Maven Clean Packages
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: Systemd Service
  ansible.builtin.include_tasks: systemd.yml

- name: Load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load
