- name: Copy Mongodb Repo File
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.pappik.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
