- name: Install Python
  ansible.builtin.yum:
    name:
    - python3-PyMySQL
    - mysql
    state: installed

- name: Load Mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: myqsql-dev.pappik.online
    login_user: root
    login_password: "{{mysql_root_password}}"