- name: Copy catalogue service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Enable, Start, Daemon-reload
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: true
    state: restarted
    enabled: yes